name: Build, Release, and Cleanup Workflow

on:
  schedule:
    - cron: "0 0 * * 1" # Runs on mondays at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-release-and-cleanup:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - run: pip install -r requirements.txt

      - name: Run data collection
        run: python -u getdata.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OSM_POI_Europe
          path: output/OSM_POI_Europe.zip
          retention-days: 7
          overwrite: true

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Updated on ${{ steps.date.outputs.date }}
          body: Automated update of OSM POI Europe on ${{ steps.date.outputs.date }}
          tag_name: v${{ steps.date.outputs.date }}
          files: output/OSM_POI_Europe.zip
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
