name: Build and Release

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run data collection
        run: python -u getdata.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OSM_POI_Europe
          path: output/OSM_POI_Europe.zip
          retention-days: 0 # Keep forever

      - name: Set build info
        id: build_info
        run: echo "job_id=${{ github.run_id }}" >> $GITHUB_OUTPUT

    outputs:
      job_id: ${{ steps.build_info.outputs.job_id }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: OSM_POI_Europe
          path: output

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Updated on ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
          body: Automated update of OSM POI Europe on ${{ steps.date.outputs.date }}
          files: output/OSM_POI_Europe.zip
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
